artifact_location: file:///Users/cchizinski2/Documents/git2/student_work/ava_britton/pradel-jax/optimization_experiments/122897001587444278
creation_time: 1755114868648
experiment_id: '122897001587444278'
last_update_time: 1755114868648
lifecycle_stage: active
name: strategy_comparison
