artifact_location: file:///Users/cchizinski2/Documents/git2/student_work/ava_britton/pradel-jax/optimization_experiments/697486183821011887
creation_time: 1755114868629
experiment_id: '697486183821011887'
last_update_time: 1755114868629
lifecycle_stage: active
name: enhanced_test
